apiVersion: v1
kind: Secret
metadata:
  name: seed
  labels:
    app: seed
type: Opaque
data:
  database-url: cG9zdGdyZXM6Ly9hcGktcGxhdGZvcm06IUNoYW5nZU1lIUAxMjcuMC4wLjE6MzMwNi9hcGk=
  secret: Q2hhbmdlTWU=
