version: "3.4"

services:
  php:
    image: ${CONTAINER_REGISTRY_BASE}/php
    build:
      context: ./backend
      target: api_platform_php
      cache_from:
        - ${CONTAINER_REGISTRY_BASE}/php
        - ${CONTAINER_REGISTRY_BASE}/nginx
        - ${CONTAINER_REGISTRY_BASE}/varnish
    depends_on:
      - db
      - db-test
    # Comment out these volumes in production
    volumes:
      - ./backend:/srv/api:rw,cached
      # If you develop on Linux, uncomment the following line to use a bind-mounted host directory instead
      # - ./backend/var:/srv/api/var:rw
    environment:
      # Specify here the IDE_KEY used in your browser
      PHP_IDE_CONFIG: serverName=PHPSTORM

  api:
    image: ${CONTAINER_REGISTRY_BASE}/nginx
    build:
      context: ./backend
      target: api_platform_nginx
      cache_from:
        - ${CONTAINER_REGISTRY_BASE}/php
        - ${CONTAINER_REGISTRY_BASE}/nginx
        - ${CONTAINER_REGISTRY_BASE}/varnish
    depends_on:
      - php
    # Comment out this volume in production
    volumes:
      - ./backend/public:/srv/api/public:ro
    ports:
      - "8000:80"

  cache-proxy:
    image: ${CONTAINER_REGISTRY_BASE}/varnish
    build:
      context: ./backend
      target: api_platform_varnish
      cache_from:
        - ${CONTAINER_REGISTRY_BASE}/php
        - ${CONTAINER_REGISTRY_BASE}/nginx
        - ${CONTAINER_REGISTRY_BASE}/varnish
    depends_on:
      - api
    volumes:
      - ./backend/docker/varnish/conf:/usr/local/etc/varnish:ro
    tmpfs:
      - /usr/local/var/varnish:exec
    ports:
      - "8081:80"

  db:
    # In production, you may want to use a managed database service
    image: postgres:10.6-alpine
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=api-platform
      # You should definitely change the password in production
      - POSTGRES_PASSWORD=!ChangeMe!
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

  db-test:
    image: postgres:10.6-alpine
    environment: # Credentials must differ from the main database in order to avoid what we call in France "Programmation par coïncidence"
    - POSTGRES_DB=seed
    - POSTGRES_USER=seed
    - POSTGRES_PASSWORD=Ge0rgesMoustaki

  h2-proxy:
    # Don't use this proxy in prod
    build:
      context: ./h2-proxy
    depends_on:
      - api
      - cache-proxy
    ports:
      - "8443:8443"
      - "8444:8444"

volumes:
  db-data: {}
